# Generated by Django 4.2.23 on 2025-07-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['user'], name='leaderboard_user_id_5306c7_idx'),
        ),
    ]
